# https://travis-ci.org

language: cpp
dist: xenial

addons:
  apt:
    update: true
    packages:
      - build-essential
      - cmake

cache:
    directories:
      - .PVS-Studio/

matrix:
  include:
    - os: linux
      compiler: "gcc"
      env: PVS_ANALYZE=Yes
    - os: linux
      compiler: "clang"

before_install:
  - travis_retry bash .travis.sh travis_before_install

install:
  - travis_retry bash .travis.sh travis_install
  - plog-converter -t errorfile PVS-Studio-${CC}.log --cerr -w

script:
  - bash .travis.sh travis_script

after_failure:
  - bash .travis.sh travis_after_failure
  