# https://travis-ci.org

language: cpp
dist: xenial

addons:
  apt:
    update: true
    packages:
      - build-essential
      - cmake
      - jq
      - wget

cache:
    directories:
      - .PVS-Studio/

git:
  fetch: false

matrix:
  include:
    - os: linux
      compiler: "gcc"
      env: PVS_ANALYZE=Yes

before_install:
  - travis_retry bash .travis.sh travis_before_install

install:
  - travis_retry bash .travis.sh travis_install

script:
  - bash .travis.sh travis_script
