pr:
  branches:
    include:
     - "*"

trigger:
  branches:
    exclude:
    - "*"
  
pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - script: |
      cmake .
    displayName: 'Generate MakeFiles'
  
  - script: |
      make
    displayName: 'Build Project'

- job: Analyze
  steps:
  - script: |
      cmake .
    displayName: 'Generate MakeFiles'
  
  - script: |
      make
    displayName: 'Build Project'

