pr:
  branches:
    include:
     - "*"

trigger:
  branches:
    exclude:
    - "*"
  
pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: A
  steps:
  - bash: echo "A"

- job: B
  steps:
  - bash: echo "B"