pr:
  branches:
    include:
     - "*"

trigger:
  branches:
    exclude:
    - "*"

jobs:
- job: build
  displayName: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=On .
  - bash: make -j8

- job: pvs_studio_analyze
  displayName: PVS-Studio Analyze
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: touch testdate
  - task: CacheBeta@0
    displayName: Cache PVS-Studio
    inputs:
      key: pvs-studio-analyzer | $(Agent.OS)
      path: $(System.DefaultWorkingDirectory)/testdate
  - bash: cat testdate
  - bash: date > testdate
  - bash: cat testdate