pr:
  branches:
    include:
     - "*"

push:
  branches: none
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cmake .
  displayName: 'Generate MakeFiles'

- script: |
    make
  displayName: 'Build Project'
