pr:
  branches:
    include:
     - "*"

trigger:
  branches:
    exclude:
    - "*"
  
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job:
      steps:
      - script: |
          cmake .
        displayName: 'Generate MakeFiles'
      
      - script: |
          make
        displayName: 'Build Project'
