pr:
  branches:
    include:
     - "*"

trigger:
  branches:
    exclude:
    - "*"

jobs:
- job: A
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: echo "A"

- job: B
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: echo "B"