version: 2.1

executors:
  main:
    docker:
      - image: "debian:stretch"

jobs:
  build:
    executor: main
    steps:
      - checkout
      - run:
          name: Update repos
          command: 'apt-get update'
      - run:
          name: Installing GCC
          command: 'apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get install -y cmake'
      - run:
          name: Generating Makefiles
          command: 'cmake .'
      - run:
          name: Compiling
          command: 'make'
      - run: pwd
      - run: ls -al
      - persist_to_workspace:
          root: ..
          paths: .

  pvs-studio-install:
    executor: main
    steps:
      - run: pwd
      - run: ls -al
      - run:
          name: Installing PVS-Studio
          command: 'apt-get install -y wget'
      - run:
          name: Add apt-keys 
          command: |
            wget -q -O - https://files.viva64.com/etc/pubkey.txt \
              | apt-key add -
            wget -O /etc/apt/sources.list.d/viva64.list \
              https://files.viva64.com/etc/viva64.list
      - run:
          name: Update repos
          command: 'apt-get update'
      - run:
          name: Installing PVS-Studio
          command: 'apt-get install -y pvs-studio'

  pvs-studio-analyze:
    executor: main
    steps:
      - run:
          name: Installing licence
          command: 'pvs-studio-analyzer credentials $PVS_USERNAME $PVS_KEY'


workflows:
  build-test:
    jobs:
      - build
      - pvs-studio-install:
          requires:
            - build
      - pvs-studio-analyze:
          requires:
            - pvs-studio-install

