version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Generating Makefiles
          command: 'cmake .'
      - run:
          name: Compiling
          command: 'make'

  pvs-studio-analyze:
    docker:
      - image: "debian:stretch"
    steps:
      - run:
          name: Test
          command: 'echo test; exit 2'


workflows:
  version: 2

  build-test:
    jobs:
      - build
      - pvs-studio-analyze:
          requires:
            - build
