version: 2.1

executors:
  main:
    docker:
      - image: buildpack-deps:jessie
    working_directory: /tmp

jobs:
  flow:
    executor: main
    steps:
      - run: ls -al
      - checkout
      - run: ls -al
      - run: mkdir -p workspace
      - run: cp main.cpp workspace/
      
      - persist_to_workspace:
          root: workspace
          paths:
            - main.cpp

  downstream:
    executor: main
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run: cat main.cpp

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
