version: 2.1

executors:
  main:
    docker:
      - image: buildpack-deps:stretch
    working_directory: /tmp/workspace

jobs:
  build:
    executor: main
    steps:
      - checkout
      - run:
          name: Update repos
          command: 'apt-get update'
      - run:
          name: Installing GCC
          command: 'apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get install -y cmake'
      - run:
          name: Generating Makefiles
          command: 'cmake .'
      - run:
          name: Compiling
          command: 'make'
      - persist_to_workspace:
          root: /tmp/workspace
          paths: 
            - ./*

  pvs-studio:
    executor: main
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Update repos
          command: 'apt-get update'
      - run:
          name: Installing utils
          command: 'apt-get install -y wget apt-transport-https jq git'
      - run:
          name: Add apt-keys 
          command: |
            wget -q -O - https://files.viva64.com/etc/pubkey.txt \
              | apt-key add -
            wget -O /etc/apt/sources.list.d/viva64.list \
              https://files.viva64.com/etc/viva64.list
      - run:
          name: Update repos
          command: 'apt-get update'
      - run:
          name: Installing PVS-Studio
          command: 'apt-get install -y pvs-studio gcc'
      - run:
          name: Installing licence
          command: 'pvs-studio-analyzer credentials $PVS_USERNAME $PVS_KEY'
      - run:
          name: Get Pull Request info
          command: |
            PULL_REQUEST_ID="pulls/${CIRCLE_PULL_REQUEST##*/}"
            REPO_SLUG="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
            MERGE_BASE=`wget -qO - https://api.github.com/repos/${REPO_SLUG}/${PULL_REQUEST_ID} | jq -r ".base.sha"`

            git diff --name-only HEAD $MERGE_BASE > .pvs-pr.list
      - run:
          name: Start PVS-Studio
          command: |
            if [[ ! -z $CIRCLE_PULL_REQUEST ]] ; then
              pvs-studio-analyzer analyze -j8 -o PVS-Studio.log --disableLicenseExpirationCheck -S .pvs-pr.list
            else
              pvs-studio-analyzer analyze -j8 -o PVS-Studio.log --disableLicenseExpirationCheck
            fi
      - run:
          name: Check results
          command: plog-converter -t errorfile PVS-Studio.log --cerr -w

workflows:
  build-test:
    jobs:
      - build
      - pvs-studio:
          requires:
            - build
