version: 2.1

executors:
  main:
    docker:
      - image: buildpack-deps:stretch
    working_directory: /tmp/workspace

jobs:
  build:
    executor: main
    steps:
      - checkout
      - run:
          name: Update repos
          command: 'apt-get update'
      - run:
          name: Installing GCC
          command: 'apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get install -y cmake'
      - run:
          name: Generating Makefiles
          command: 'cmake .'
      - run:
          name: Compiling
          command: 'make'
      - persist_to_workspace:
          root: /tmp/workspace
          paths: 
            - ./*

  pvs-studio:
    executor: main
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Update repos
          command: 'apt-get update'
      - run:
          name: Installing utils
          command: 'apt-get install -y wget apt-transport-https'
      - run:
          name: Add apt-keys 
          command: |
            wget -q -O - https://files.viva64.com/etc/pubkey.txt \
              | apt-key add -
            wget -O /etc/apt/sources.list.d/viva64.list \
              https://files.viva64.com/etc/viva64.list
      - run:
          name: Update repos
          command: 'apt-get update'
      - run:
          name: Installing PVS-Studio
          command: 'apt-get install -y pvs-studio gcc'
      - run:
          name: Installing licence
          command: 'pvs-studio-analyzer credentials $PVS_USERNAME $PVS_KEY'
      - run:
          name: Installing licence
          command: 'pvs-studio-analyzer credentials $PVS_USERNAME $PVS_KEY'
      - run: 'echo $CIRCLE_PR_NUMBER and $CIRCLE_BRANCH'


workflows:
  build-test:
    jobs:
      - build
      - pvs-studio:
          requires:
            - build
