version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Generating Makefiles
          command: 'cmake .'
      - run:
          name: Compiling
          command: 'make'

  pvs-studio-install:
    docker:
      - image: "debian:stretch"
    steps:
      - run:
          name: Add apt-keys 
          command: |
            wget -q -O - https://files.viva64.com/etc/pubkey.txt \
              | sudo apt-key add -
            sudo wget -O /etc/apt/sources.list.d/viva64.list \
              https://files.viva64.com/etc/viva64.list
      - run:
          name: Installing PVS-Studio
          command: 'apt-get update && apt-get install -y pvs-studio'

  pvs-studio-analyze:
    docker:
      - image: "debian:stretch"
    steps:
      - run:
          name: Installing licence
          command: 'pvs-studio-analyzer credentials $PVS_USERNAME $PVS_KEY'


workflows:
  version: 2

  build-test:
    jobs:
      - build
      - pvs-studio-install:
          requires:
            - build
      - pvs-studio-analyze:
          requires:
            - pvs-studio-install

