version: 2.1

executors:
  main:
    docker:
      - image: buildpack-deps:jessie
    working_directory: /tmp/workspace

jobs:
  flow:
    executor: main
    steps:
      - run: ls -al
      - checkout
      - run: ls -al
      - run: mkdir -p workspace2
      - run: cp main.cpp workspace2/
      
      - persist_to_workspace:
          root: workspace2
          paths:
            - main.cpp

  downstream:
    executor: main
    steps:
      - attach_workspace:
          at: /tmp/workspace/workspace2

      - run: cat main.cpp

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
