version: 2.1

executors:
  main:
    docker:
      - image: "debian:stretch"
    working_directory: /tmp/workspace

jobs:
  flow:
    executor: main
    steps:
      - run: ls -al
      - checkout
      - run: ls -al
      
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - main.cpp

  downstream:
    executor: main
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run: cat main.cpp

workflows:
  version: 2

  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow
